//Paste your list generated by voluntyranator_stuff > classfilemaker.html in here, then save this file.



var myClass = [
	"Megha Ainikunnath Kamalan",
	"Spencer Dowie",
	"Jursida Hima",
	"Taranpreet Kaur",
	"Ravi Kumar",
	"Kantima EMMY Pinthong",
	"Rinzin Rinzin",
	"Lovepreet Sandhu",
	"robinson voranzov",
	"Joseph Bonachea"
];